### ISSUE TITLE
Plant datasets

### ISSUE THREAD

**Issue by roomfortwo** [BenKaehler/readytowear#10]
Hello there, 
Quick questions, 
1. when it says plant corpus, does it refer to the whole plant or some specific parts (I have a leaf and root 16s amplicons); 
2. Is it possible to combine two or more datasets into something more comprenhensive? 

Cheers, 
Luis Alfonso.

**Comment by nbokulich** [comment]
Hi @roomfortwo,
1. you should refer to the EMP project for a complete description (as this empo_3 type is defined there) but yes "plant corpus" refers to the whole plant or possibly vouchered specimens. If you have leaf and root it might be better to create custom weights.
2. in theory yes, but this is where making custom weights may be more beneficial to select ideal samples for assembling weights
