### ISSUE TITLE
Taxonomic weight for animal fecal samples

### ISSUE THREAD

**Issue by stephgarcia1201** [BenKaehler/readytowear#13]
Hoping you can help clarify which taxonomic weight .qza file to use for mouse fecal samples. Animal-distal-gut or animal-secretion?

**Comment by BenKaehler** [comment]
Hi @stephgarcia1201, that would be animal-distal-gut.

**Comment by BenKaehler** [comment]
Hi @stephgarcia1201, if you're interested in compiling mouse-fecal specific weights, it could be done fairly easily by following the [clawback tutorial](https://forum.qiime2.org/t/using-q2-clawback-to-assemble-taxonomic-weights/5859).

Specifically, in the "Assembling more exotic weights" script, you could replace the first command with

```
redbiom search metadata "where host_taxid==10090  and (sample_type=='stool' or sample_type=='Stool')" > sample_ids
```

**Comment by stephgarcia1201** [comment]
Awesome! Appreciate the help.
