### ISSUE TITLE
Compatibility of silva v138.1 with class-weights based on v138

### ISSUE THREAD

**Issue by ARW-UBT** [BenKaehler/readytowear#19]
Hi, is it possible to use silva v138.1 reference seqs and taxonomies together with class-weights available in your readytowear inventory, which are based on v138?
Thanks for this great tools!

**Comment by nbokulich** [comment]
answered on the QIIME 2 forum: https://forum.qiime2.org/t/reference-db-compatibility-silva-138-138-1/21913
