### ISSUE TITLE
Animals in animal-distal-gut?

### ISSUE THREAD

**Issue by msmcfarlin** [BenKaehler/readytowear#23]
Hello,

I am doing microbiome analysis on samples from tenrecs. I am curious what animals are represented by the animal distal gut weights and if you think this file would be appropriate to use on my samples since the tenrec group is likely poorly represented in reference databases.

Thank you!

**Comment by nbokulich** [comment]
Hi @msmcfarlin ,
these weights were built from the Earth Microbiome Project dataset, so you can check the metadata from that project to look at the distribution of different host species. I do not know off-hand, but I would imagine that the data contain a higher proportion of homo sapiens than other animal species. For focusing on tenrecs or any other specific clade, you might want to try making your own weights (see the QIIME 2 forum for a tutorial about this), provided that you can find sufficient source data (from tenrecs or related mammals)... it could be interesting to compare this vs. the readytowear weights to see if you get more credible results (I am assuming that you do not have a groundtruth).

Nevertheless, these weights are probably better than nothing (i.e., using a uniform prior), unless if tenrecs are very very different (microbiologically speaking) from other mammals.
